### ISSUE TITLE
Expanding subviews in UICollectionViewCell

### ISSUE THREAD

**Issue by laurent-humbert** [asynchrony/Re-Lax#1]
Just implemented Re:Lax and it looks great. Thanks

I use a ParallaxContainer in my CollectionViewCell, just like in your example. Works great, except for one problem: how can I prevent a subview from "expanding" when the cell is focussed ?

Here's an example:

![screen shot 2017-04-08 at 13 14 31](https://cloud.githubusercontent.com/assets/19427074/24828478/5b28e7a4-1c5e-11e7-9330-38f6c70d161a.png)

Here the red UIView has a constraint so that its leading lines up with the "APP STORE" label, and the trailing of the "8:AM", but when focused this is no longer the case.

Again, thanks for the great work. If you'd like to Testflight the app, let me know I'd be happy to add your email to the list.

**Comment by JARinteractive** [comment]
The Parallax effect is created by zooming each layer (subviews of the ParallaxContainer) by a different amount and then translating them as the view is transformed. You can put views in a common parent (that is then added as a subview of the container) to give the appearance of being on the same layer.

**Comment by laurent-humbert** [comment]
Thanks very much, I'll try that.
